name: CI workflow
on: push
jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'

    name: CI workflow on PHP ${{ matrix.php-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: php-cs-fixer

      - name: Debug PHP installation
        run: |
          composer --version
          php --version
          php --modules

      - name: Validate composer files
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: composer run test

      - name: Run php-cs-fixer
        run: php-cs-fixer fix --dry-run --diff --diff-format udiff

